### ISSUE TITLE
syntax error on type 

### ISSUE THREAD

**Issue by grzegorzbieszczad** [ZZZZzzzzac/numfi#5]
my Python 3.10.12 fails on:
from typing import Literal
type RoundingMethod_Enum = Literal['Nearest', 'Round', 'Convergent','Floor','Zero','Ceiling']
type OverflowAction_Enum = Literal['Error','Wrap','Saturate']
it seems to be a syntax error. Removing **type** keyword fixes the problem.
As my error message was ambiguous, here some ChatGPT wisdom on the code:
"In Python, type is a built-in function and cannot be used to define a type alias. Instead, you should use the = operator to create a type alias."

**Comment by ZZZZzzzzac** [comment]
thanks for reporting, but it seems like a syntax change from python 3.10 to 3.12, the example in [3.12 docs](https://docs.python.org/3.12/library/typing.html#typing.Literal) and [3.10 docs](https://docs.python.org/3.10/library/typing.html#typing.Literal) shows the same thing.
But anyway, that problem is only about typing and does not affect the function of numfi, you can change/remove it as you like
